-------------------------------------------------------------------
-- MobileWhere Server Creation Script                            --
-------------------------------------------------------------------
-- Versión: 3.0                                                  --
-- Última revisión: 09/05/2008                                   --
-------------------------------------------------------------------
-- Copyright © 2008 Offshore Tech S.L.                           --
-------------------------------------------------------------------

CREATE TABLE [dbo].[AUTHORS] (
	[AUTHORID] [int] IDENTITY (1, 1) NOT NULL ,
	[AUTHORNAME] [nvarchar] (128) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[AUTHORSIGN] [ntext] COLLATE Modern_Spanish_CI_AS NOT NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[CODETAGS] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[NAME] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[AUTHOR] [smallint] NULL ,
	[TYPE] [int] NOT NULL ,
	[SOURCE] [ntext] COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[DESCRIPTION] [ntext] COLLATE Modern_Spanish_CI_AS NOT NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[COMMANDS] (
	[SCMDID] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SCSERVICEID] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SCPARENTID] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SCNAME] [nvarchar] (128) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SCTYPE] [int] NOT NULL ,
	[SCSOURCE] [ntext] COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SCCLASS] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[HELP] (
	[BOKID] [int] IDENTITY (1, 1) NOT NULL ,
	[BOKPARENTID] [int] NOT NULL ,
	[BOKNAME] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[BOKFILE] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[BOKORDER] [int] NOT NULL ,
	[BOKADMIN] [bit] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ROLES] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[NAME] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[DESCRIPTION] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[ISADMIN] [bit] NOT NULL ,
	[ENABLED] [bit] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ROLESDET] (
	[ROLEID] [int] NOT NULL ,
	[OBJECTID] [nvarchar] (128) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[GRANTED] [bit] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SERVERAPPS] (
	[SERVERID] [int] NOT NULL ,
	[APPID] [int] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SERVERS] (
	[SRVID] [int] IDENTITY (1, 1) NOT NULL ,
	[SRVNAME] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SRVDBSERVER] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SRVDBSOURCE] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SRVDBDRIVER] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SRVDBUSER] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SRVDBPWD] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SRVFSROOT] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SRVURLROOT] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SERVICES] (
	[SSID] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SSNAME] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SSPARENTID] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NULL ,
	[SSMANAGER] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SSHELP] [int] NOT NULL ,
	[SSTYPE] [int] NOT NULL ,
	[SSFILE] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SSVER] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SSPLATFORM] [int] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SERVICE_TYPES] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[NAME] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[DESCRIPTION] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[LICENCEKEY] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[LICENCES] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[TSQL] [ntext] COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[PACKET] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[STD_BANNER] (
	[STDSERVER] [int] NOT NULL ,
	[STDBANNER] [int] NOT NULL ,
	[STDDATE] [smalldatetime] NOT NULL ,
	[STDNAME] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[STDCLICKS] [int] NOT NULL ,
	[STDSHOWS] [int] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TEMPLATES] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[NAME] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[DESCRIPTION] [nvarchar] (2048) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[AUTHOR] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[VERSION] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[FILE] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[PLATFORM] [int] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USERS] (
	[USRLOGIN] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[USRROLEID] [int] NOT NULL ,
	[USRPWD] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[USRNAME] [nvarchar] (128) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[USRDESC] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[USRMAIL] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[USRADMIN] [bit] NOT NULL ,
	[USRDISABLED] [bit] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[VALUES] (
	[SVPARAM] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SVVALUE] [ntext] COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SVDESC] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[SVPUBLIC] [bit] NOT NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[VIEWERS] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[SERVICEID] [nvarchar] (64) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[NAME] [nvarchar] (128) COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[DESCRIPTION] [ntext] COLLATE Modern_Spanish_CI_AS NOT NULL ,
	[FILENAME] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[AUTHORS] WITH NOCHECK ADD 
	CONSTRAINT [PK_AUTHORS] PRIMARY KEY  CLUSTERED 
	(
		[AUTHORID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CODETAGS] WITH NOCHECK ADD 
	CONSTRAINT [PK_CODETAGS] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[COMMANDS] WITH NOCHECK ADD 
	CONSTRAINT [PK_COMMANDS] PRIMARY KEY  CLUSTERED 
	(
		[SCMDID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[HELP] WITH NOCHECK ADD 
	CONSTRAINT [PK_HELP] PRIMARY KEY  CLUSTERED 
	(
		[BOKID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ROLES] WITH NOCHECK ADD 
	CONSTRAINT [PK_ROLES] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ROLESDET] WITH NOCHECK ADD 
	CONSTRAINT [PK_ROLESDET] PRIMARY KEY  CLUSTERED 
	(
		[ROLEID],
		[OBJECTID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SERVERAPPS] WITH NOCHECK ADD 
	CONSTRAINT [PK_SERVERAPPS] PRIMARY KEY  CLUSTERED 
	(
		[SERVERID],
		[APPID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SERVERS] WITH NOCHECK ADD 
	CONSTRAINT [PK_SERVERS] PRIMARY KEY  CLUSTERED 
	(
		[SRVID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SERVICES] WITH NOCHECK ADD 
	CONSTRAINT [PK_SERVICES] PRIMARY KEY  CLUSTERED 
	(
		[SSID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SERVICE_TYPES] WITH NOCHECK ADD 
	CONSTRAINT [PK_SERVICE_TYPES] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STD_BANNER] WITH NOCHECK ADD 
	CONSTRAINT [PK_STD_BANNER] PRIMARY KEY  CLUSTERED 
	(
		[STDSERVER],
		[STDBANNER],
		[STDDATE]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TEMPLATES] WITH NOCHECK ADD 
	CONSTRAINT [PK_TEMPLATES] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[USERS] WITH NOCHECK ADD 
	CONSTRAINT [PK_USERS] PRIMARY KEY  CLUSTERED 
	(
		[USRLOGIN]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[VALUES] WITH NOCHECK ADD 
	CONSTRAINT [PK_VALUES] PRIMARY KEY  CLUSTERED 
	(
		[SVPARAM]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[VIEWERS] WITH NOCHECK ADD 
	CONSTRAINT [PK_VIEWERS] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CODETAGS] ADD 
	CONSTRAINT [DF_CODETAGS_AUTHOR] DEFAULT (0) FOR [AUTHOR],
	CONSTRAINT [DF_CODETAGS_TYPE] DEFAULT (0) FOR [TYPE],
	CONSTRAINT [DF_CODETAGS_SOURCE] DEFAULT ('') FOR [SOURCE],
	CONSTRAINT [DF_CODETAGS_DESCRIPTION] DEFAULT ('') FOR [DESCRIPTION]
GO

ALTER TABLE [dbo].[COMMANDS] ADD 
	CONSTRAINT [DF_COMMANDS_SCPARENTID] DEFAULT ('') FOR [SCPARENTID],
	CONSTRAINT [DF_COMMANDS_SCTYPE] DEFAULT (0) FOR [SCTYPE],
	CONSTRAINT [DF_COMMANDS_SCSOURCE] DEFAULT ('') FOR [SCSOURCE],
	CONSTRAINT [DF_COMMANDS_SCCLASS] DEFAULT ('') FOR [SCCLASS]
GO

 CREATE  INDEX [IX_COMMANDS_SERVICEID] ON [dbo].[COMMANDS]([SCSERVICEID]) ON [PRIMARY]
GO

 CREATE  INDEX [IX_COMMANDS_PARENTID] ON [dbo].[COMMANDS]([SCPARENTID]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HELP] ADD 
	CONSTRAINT [DF_HELP_BOKORDER] DEFAULT (0) FOR [BOKORDER],
	CONSTRAINT [DF_HELP_BOKADMIN] DEFAULT (0) FOR [BOKADMIN]
GO

 CREATE  INDEX [IX_HELP_PARENTID] ON [dbo].[HELP]([BOKPARENTID]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ROLES] ADD 
	CONSTRAINT [DF_ROLES_DESCRIPTION] DEFAULT ('') FOR [DESCRIPTION]
GO

ALTER TABLE [dbo].[SERVERS] ADD 
	CONSTRAINT [DF_SERVERS_SRVDBSERVER] DEFAULT ('') FOR [SRVDBSERVER],
	CONSTRAINT [DF_SERVERS_SRVDBSOURCE] DEFAULT ('') FOR [SRVDBSOURCE],
	CONSTRAINT [DF_SERVERS_SRVDBDRIVER] DEFAULT ('') FOR [SRVDBDRIVER],
	CONSTRAINT [DF_SERVERS_SRVDBUSER] DEFAULT ('') FOR [SRVDBUSER],
	CONSTRAINT [DF_SERVERS_SRVDBPWD] DEFAULT ('') FOR [SRVDBPWD],
	CONSTRAINT [DF_SERVERS_SRVFSROOT] DEFAULT ('') FOR [SRVFSROOT],
	CONSTRAINT [DF_SERVERS_SRVURLROOT] DEFAULT ('') FOR [SRVURLROOT]
GO

ALTER TABLE [dbo].[SERVICES] ADD 
	CONSTRAINT [DF_SERVICES_SSPARENTID] DEFAULT ('') FOR [SSPARENTID],
	CONSTRAINT [DF_SERVICES_SSHELP] DEFAULT (0) FOR [SSHELP],
	CONSTRAINT [DF_SERVICES_SSTYPE] DEFAULT (0) FOR [SSTYPE],
	CONSTRAINT [DF_SERVICES_SSFILE] DEFAULT ('') FOR [SSFILE],
	CONSTRAINT [DF_SERVICES_SSVER] DEFAULT ('1.0') FOR [SSVER],
	CONSTRAINT [DF_SERVICES_SSPLATFORM] DEFAULT (0) FOR [SSPLATFORM]
GO

 CREATE  INDEX [IX_SERVICES_PARENTID] ON [dbo].[SERVICES]([SSPARENTID]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SERVICE_TYPES] ADD 
	CONSTRAINT [DF_SERVICE_TYPES_DESCRIPTION] DEFAULT ('') FOR [DESCRIPTION],
	CONSTRAINT [DF_SERVICE_TYPES_LICENCEKEY] DEFAULT ('') FOR [LICENCEKEY],
	CONSTRAINT [DF_SERVICE_TYPES_LICENCES] DEFAULT ('') FOR [LICENCES],
	CONSTRAINT [DF_SERVICE_TYPES_SQL] DEFAULT ('') FOR [TSQL],
	CONSTRAINT [DF_SERVICE_TYPES_PACKET] DEFAULT ('') FOR [PACKET]
GO

ALTER TABLE [dbo].[STD_BANNER] ADD
	CONSTRAINT [DF_STD_BANNER_STDNAME] DEFAULT ('') FOR [STDNAME],
	CONSTRAINT [DF_STD_BANNER_STDCLICKS] DEFAULT (0) FOR [STDCLICKS],
	CONSTRAINT [DF_STD_BANNER_STDSHOWS] DEFAULT (0) FOR [STDSHOWS]
GO

ALTER TABLE [dbo].[TEMPLATES] ADD
	CONSTRAINT [DF_TEMPLATES_DESCRIPTION] DEFAULT ('') FOR [DESCRIPTION],
	CONSTRAINT [DF_TEMPLATES_AUTHOR] DEFAULT ('') FOR [AUTHOR],
	CONSTRAINT [DF_TEMPLATES_VERSION] DEFAULT ('1.0') FOR [VERSION],
	CONSTRAINT [DF_TEMPLATES_FILE] DEFAULT ('') FOR [FILE],
	CONSTRAINT [DF_TEMPLATES_PLATFORM] DEFAULT (0) FOR [PLATFORM]
GO

ALTER TABLE [dbo].[USERS] ADD
	CONSTRAINT [DF_USERS_USRPWD] DEFAULT ('') FOR [USRPWD],
	CONSTRAINT [DF_USERS_USRNAME] DEFAULT ('') FOR [USRNAME],
	CONSTRAINT [DF_USERS_USRDESC] DEFAULT ('') FOR [USRDESC],
	CONSTRAINT [DF_USERS_USRMAIL] DEFAULT ('') FOR [USRMAIL],
	CONSTRAINT [DF_USERS_USRADMIN] DEFAULT (0) FOR [USRADMIN],
	CONSTRAINT [DF_USERS_USRDISABLED] DEFAULT (0) FOR [USRDISABLED]
GO

 CREATE  INDEX [IX_USERS_ROLEID] ON [dbo].[USERS]([USRROLEID]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VALUES] ADD 
	CONSTRAINT [DF_VALUES_SVDESC] DEFAULT ('') FOR [SVDESC],
	CONSTRAINT [DF_VALUES_SVPUBLIC] DEFAULT (1) FOR [SVPUBLIC]
GO

ALTER TABLE [dbo].[VIEWERS] ADD 
	CONSTRAINT [DF_VIEWERS_DESCRIPTION] DEFAULT ('') FOR [DESCRIPTION]
GO

 CREATE  INDEX [idx_VIEWERS_SERVICEID] ON [dbo].[VIEWERS]([SERVICEID]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMMANDS] ADD 
	CONSTRAINT [FK_COMMANDS_SERVICES] FOREIGN KEY 
	(
		[SCSERVICEID]
	) REFERENCES [dbo].[SERVICES] (
		[SSID]
	) ON UPDATE CASCADE 
GO

ALTER TABLE [dbo].[ROLESDET] ADD 
	CONSTRAINT [FK_ROLESDET_ROLES] FOREIGN KEY 
	(
		[ROLEID]
	) REFERENCES [dbo].[ROLES] (
		[ID]
	) ON UPDATE CASCADE 
GO

ALTER TABLE [dbo].[SERVERAPPS] ADD 
	CONSTRAINT [FK_SERVERAPPS_SERVERS] FOREIGN KEY 
	(
		[SERVERID]
	) REFERENCES [dbo].[SERVERS] (
		[SRVID]
	) ON DELETE CASCADE  ON UPDATE CASCADE ,
	CONSTRAINT [FK_SERVERAPPS_SERVICE_TYPES] FOREIGN KEY 
	(
		[APPID]
	) REFERENCES [dbo].[SERVICE_TYPES] (
		[ID]
	) ON DELETE CASCADE  ON UPDATE CASCADE 
GO

ALTER TABLE [dbo].[SERVICES] ADD 
	CONSTRAINT [FK_SERVICES_SERVICE_TYPES] FOREIGN KEY 
	(
		[SSTYPE]
	) REFERENCES [dbo].[SERVICE_TYPES] (
		[ID]
	) ON UPDATE CASCADE 
GO

ALTER TABLE [dbo].[USERS] ADD 
	CONSTRAINT [FK_USERS_ROLES] FOREIGN KEY 
	(
		[USRROLEID]
	) REFERENCES [dbo].[ROLES] (
		[ID]
	)
GO

-------------------------------------------------------------------
-- Copyright © 2008 Offshore Tech S.L.                           --
-------------------------------------------------------------------
