tinyMCE.addI18n('en.advlink_dlg',{
title:"Insertar/editar enlace",
url:"URL del enlace",
target:"Target",
titlefield:"Título",
is_email:"La URL especificada parece ser una cuenta de correo. ¿Desea agregar el prefijo 'mailto:'?",
is_external:"La URL especificada parece un enlace externo, ¿Desea agregar el prefijo 'http://'?",
list:"Lista de enlaces",
general_tab:"General",
popup_tab:"Popup",
events_tab:"Eventos",
advanced_tab:"Avanzado",
general_props:"Propiedades generales",
popup_props:"Propiedades del Popup",
event_props:"Eventos",
advanced_props:"Propiedades avanzadas",
popup_opts:"Opciones",
anchor_names:"Anclas",
target_blank: "Abrir en nueva ventana",
target_same:"Abrir en la misma ventana / frame",
target_parent:"Abrir el la ventana pariente / frame",
target_top:"Open in top frame (replaces all frames)",
popup:"Javascript popup",
popup_url:"Popup URL",
popup_name:"Window name",
popup_return:"Insert 'return false'",
popup_scrollbars:"Show scrollbars",
popup_statusbar:"Show status bar",
popup_toolbar:"Show toolbars",
popup_menubar:"Show menu bar",
popup_location:"Show location bar",
popup_resizable:"Make window resizable",
popup_dependent:"Dependent (Mozilla/Firefox only)",
popup_size:"Size",
popup_position:"Position (X/Y)",
id:"Id",
style:"Style",
classes:"Classes",
target_name:"Target name",
langdir:"Language direction",
target_langcode:"Target language",
langcode:"Language code",
encoding:"Target character encoding",
mime:"Target MIME type",
rel:"Relationship page to target",
rev:"Relationship target to page",
tabindex:"Tabindex",
accesskey:"Accesskey",
ltr:"Left to right",
rtl:"Right to left",
link_list:"Link list"
});